use_augmentation: true
batch_size: 32
epochs: 1000
resize_shape: [224, 224]
initial_learning_rate: 0.0001
model_path: "image_representation.h5"
image_model_path: "image_representation.h5"
label_embedding_path: "labels.json"
data_path: "/media/ml/data_ml/openimage/"