resize_shape: [224, 224]
model_path: "model.h5"
image_model_path: "image_representation.h5"
label_embedding_path: "labels.json"
model_url: "https://github.com/CVxTz/TagSuggestionImages/releases/download/v0.1/model.h5"
model_sha256: "8630647f068fc82fa8678d3807154e84c715d3d7ef8348d9caf542a670a7bc7e"
image_model_model_url: "https://github.com/CVxTz/TagSuggestionImages/releases/download/v0.1/image_representation.h5"
image_model_sha256: "c1fbeb320d7b81c118e7f76ad19eb11355521798c3cd3269a64aae36f8dd236e"
label_embedding_url: "https://github.com/CVxTz/TagSuggestionImages/releases/download/v0.1/labels.json"
label_embedding_sha256: "9616ab9287d0f1e9883c8036512ba858ab56c9765ef72dfdbac057737737f683"